### ISSUE TITLE
Not repleacing srcset

### ISSUE THREAD

**Issue by marcporcar** [ryanpcmcquen/import-external-attachments#11]
Hi,

The plugin is working like a charm but we realized that images with srcset the plugin don't recognize them and don't replace it.

It is possible to update the plugin with this feature?

Thanks.
[descarga 1](https://user-images.githubusercontent.com/30336279/28452294-531dc594-6df2-11e7-9fad-09f2295b0f74.png)

**Comment by ryanpcmcquen** [comment]
Unfortunately we have tried to accomplish this but it is not as trivial as it sounds, for that reason we recommend this plugin instead:
https://wordpress.org/plugins/image-teleporter/
