### ISSUE TITLE
Fails for most AWS or CDN images

### ISSUE THREAD

**Issue by kwoodall** [ryanpcmcquen/import-external-attachments#15]
As the title says, it's having problems importing images, or even seeing those as importable images, from AWS and CDN links. For example...

<img class="stretch-img hide@m-" src="https://o.aolcdn.com/images/dims?quality=85&amp;image_uri=https%3A%2F%2Fo.aolcdn.com%2Fimages%2Fdims%3Fresize%3D2000%252C2000%252Cshrink%26image_uri%3Dhttps%253A%252F%252Fs.yimg.com%252Fos%252Fcreatr-uploaded-images%252F2019-02%252F0a3d4f50-36ed-11e9-befb-1c1306576e00%26client%3Da1acac3e1b3290917d92%26signature%3D1c06bc881e2db5c7fc95c634a62bd1da5dc05556&amp;client=amp-blogside-v2&amp;signature=4db1418fde16f752dff52c2cab73f4fd71386a08" />

<img class="stretch-img" src="https://o.aolcdn.com/images/dims?crop=1600%2C1067%2C0%2C0&amp;quality=85&amp;format=jpg&amp;resize=1600%2C1067&amp;image_uri=http%3A%2F%2Fo.aolcdn.com%2Fhss%2Fstorage%2Fmidas%2Fa3bf5392ec4303d9298102060ac3df33%2F206709011%2FIMG_1451e.JPG&amp;client=a1acac3e1b3290917d92&amp;signature=63eff7e3706898fe405727fcb61813f61fdb4577" />

**Comment by ryanpcmcquen** [comment]
Per the description:
DEPRECATED! Use: https://wordpress.org/plugins/image-teleporter

**Comment by kwoodall** [comment]
Thanks. That's even worse. It erases the link leaving some random symbols. Which is why, as I now remeber, I was using this plugin. It was more reliable.

**Comment by kwoodall** [comment]
Image Teleporter is no longer being maintained either. Hopefully someone might pick this up and branch it.

**Comment by ryanpcmcquen** [comment]
@kwoodall, let me know if you find something better! I would be willing to transfer this to anyone who wants it also.
