### ISSUE TITLE
Imported the images only from the latest 6 posts

### ISSUE THREAD

**Issue by sapundziev** [ryanpcmcquen/import-external-attachments#2]
Hi,

great work with this plugin. For me the problem is that after importing the images from the latest 6 posts it says no more images to import. Any help would be highly appreciated.

WP version 4.4.2
Plugin version 1.5.9

Thanks

**Comment by ryanpcmcquen** [comment]
Did you refresh the page? Often it can only import so many at a time. After refreshing it should show any _remaining_ imports.

You may need to refresh & import a few times on larger sites.

**Comment by sapundziev** [comment]
When first loaded the plugin page (Media -> Import attachments) only 6 posts were there (my site has 200+).
After several refresh and import operation the external images of these posts where imported.
Once this finished i can see only the message:
Process all posts
We didn't find any external attachments to import. You're all set!

But I have many external images that should be imported. Any hints what can I do to make this work?

Thanks

**Comment by ryanpcmcquen** [comment]
What are the 2 sites involved in this import?

**Comment by sapundziev** [comment]
My blog is https://themagicoftraveling.com/ 
After many refresh requests it looks like all my photos are self hosted now. Do you know a way how can a verify that I don't link external ones?

Thanks

**Comment by ryanpcmcquen** [comment]
Is that the site you are importing to or the site you were importing from? It sounds like the problem was solved and it was merely an issue with not refreshing enough.

The plugin limits the number of images it can import at once to keep the server from killing the import process (most hosting environments put some kind of limit on these types of transfers, so this is the only way it can work ... unfortunately). It may also be that your images were on the larger side, which would mean more refreshes as well. If you get a chance you may want to optimize those images at some point, you can try my image optimizer if you are comfortable with the command line:

https://github.com/ryanpcmcquen/image-ultimator

**Comment by sapundziev** [comment]
themagic of traveling is my site and I want to import photos to it.
The photos should be imported from googleusercontent.com. 

The problem is now that the refresh doesn't show any photos to import and in the same time in my db I can see arount 5000 photos still hosted there (googleusercontent.com)

**Comment by ryanpcmcquen** [comment]
Is it possible those photos are behind some kind of redirect wall? If you try to download them using something like `wget`, how many times are you redirected before you get the file?

**Comment by sapundziev** [comment]
:~$ wget https://lh3.googleusercontent.com/-aq60Zeb8X0o/VcfB5gh9n9I/AAAAAAACIIY/j8Flo6FX6Zo/s512-Ic42/2015_08_09_23_10_57.jpg
--2016-04-12 16:42:04--  https://lh3.googleusercontent.com/-aq60Zeb8X0o/VcfB5gh9n9I/AAAAAAACIIY/j8Flo6FX6Zo/s512-Ic42/2015_08_09_23_10_57.jpg
Resolving lh3.googleusercontent.com (lh3.googleusercontent.com)... 216.58.211.1, 2a00:1450:4016:803::2001
Connecting to lh3.googleusercontent.com (lh3.googleusercontent.com)|216.58.211.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75110 (73K) [image/jpeg]
Saving to: ‘2015_08_09_23_10_57.jpg’

100%[======================================>] 75.110      --.-K/s   in 0,08s   

2016-04-12 16:42:04 (905 KB/s) - ‘2015_08_09_23_10_57.jpg’ saved [75110/75110]

**Comment by ryanpcmcquen** [comment]
And what is the site these are coming from?

**Comment by sapundziev** [comment]
Not sure I got the question :) but the images are hosted on picasaweb.google.com and these are the direct urls. I'm linking them from my blog and now I want to import them on my server and delete them from picasa.

**Comment by ryanpcmcquen** [comment]
Are they parse-able through public HTML pages? If not, they probably aren't going to work with the plugin.

**Comment by sapundziev** [comment]
Yes they are in the public posts and in the html they look like 
<img class=""aligncenter"" src=""https://lh3.googleusercontent.com/-aq60Zeb8X0o/VcfB5gh9n9I/AAAAAAACIIY/j8Flo6FX6Zo/s512-Ic42/2015_08_09_23_10_57.jpg"" alt="""" width=""343"" height=""512"" />

Also the blog posts that the plugin succeeded to import from were with the same source.

**Comment by ryanpcmcquen** [comment]
What are the URLs you are pointing the plugin to?

**Comment by sapundziev** [comment]
I'm just opening Media->Import attachments
and expect to see list of posts which have external attachments in them.

But there is nothing there now.

> Process all posts
> 
> We didn't find any external attachments to import. You're all set!

**Comment by ryanpcmcquen** [comment]
Will you point me to a post that you are sure hasn't been imported? I will investigate further.

**Comment by sapundziev** [comment]
I took a deep dive in my db and it turned out that the many external images are from only one post with many revisions. So I just fixed them manually and now it is all good. Thank you for your help and for the great plugin you are trying to keep alive :)

**Comment by ryanpcmcquen** [comment]
I'm glad you got it working!

This issue will be useful for other people having the same problem. Thanks for reporting it!

**Comment by infathomable** [comment]
Hi, I had the same issue. After digging into my posts, found out that the plugin doesn't detect images starting with "https". If i manually change the url to "http" it shows images to import. Any workaround ?

**Comment by ryanpcmcquen** [comment]
Hi @infathomable, I was able to import `https` photos, will you send me a link to one of your posts?

**Comment by infathomable** [comment]
I've replaced all the 'https' urls to 'http' in the database and imported all the images. Thanks :)
