### ISSUE TITLE
not recognizing images jpg?hadau56

### ISSUE THREAD

**Issue by erikvanberkum** [ryanpcmcquen/import-external-attachments#7]
When a file or image with extension any extension is followed by a ? ie. .jpg?a7dha or .png?ahsdkh it is not recognized as an importable image. 

To solve this issue all characters after the ? including the questions mark should be omitted

**Comment by ryanpcmcquen** [comment]
Pull request?

**Comment by ryanpcmcquen** [comment]
Closing this is in favor of https://github.com/ryanpcmcquen/import-external-attachments/issues/9
